# Generated by Django 3.1.1 on 2020-09-08 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meal',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='meal',
            name='difficulty',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meal',
            name='healthiness',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='meal',
            constraint=models.CheckConstraint(check=models.Q(difficulty__range=(0, 10)), name='difficulty_between_0_and_10'),
        ),
        migrations.AddConstraint(
            model_name='meal',
            constraint=models.CheckConstraint(check=models.Q(healthiness__range=(0, 10)), name='healthiness_between_0_and_10'),
        ),
    ]
