# Generated by Django 3.1.1 on 2020-09-21 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0003_auto_20200921_1903'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mealplan',
            options={'ordering': ['start_date']},
        ),
    ]
